### ISSUE TITLE
Default value tooltip

### ISSUE THREAD

**Issue by MaKiPL** [alexfilth/doomtrain#1]
Add default values tooltip by reparsing innerbuilt original kernel.bin file

**Comment by MaKiPL** [comment]
Just to say - this has to be done after finishing whole soft. 
Maybe embeed it in resources file and save to static byte[] just before program InitializeComponent(), after that just easy - use already built-in function but instead use the other byte array (the one with original values)

**Comment by DarkShinryu** [comment]
Covarr has informed me that if the editor had the kernel.bin in it they would not allow the distribution on Qhimm forums, i guess we'll have to pass on this idea. :P

**Comment by MaKiPL** [comment]
No way. ^_^
If we cannot distribute soft with embedded kernel.bin, then the soft will generate one for itself at first run and will always use that secret backup. Question is- where to store the file. In temp?

**Comment by DarkShinryu** [comment]
That sounds like a good alternative.

**Comment by MaKiPL** [comment]
I think %TEMP% tends to be a good place to store it. There's a lot to do (adding tooltip to every control), so I might start doing this soon.

**Comment by DarkShinryu** [comment]
I added almost all the kernel data sections, i'll probably finish in a couple of days. I'll write another message here when i'm done.

**Comment by DarkShinryu** [comment]
Ok all kernel sections are added, you can start when you want. :)
